#version 450
layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(binding = 2, std430) writeonly buffer Output
{
    float result[];
} _20;

layout(binding = 0, std430) readonly buffer InputA
{
    float dataA[];
} _27;

layout(binding = 1, std430) readonly buffer InputB
{
    float dataB[];
} _35;

void main()
{
    uint idx = gl_GlobalInvocationID.x;
    _20.result[idx] = _27.dataA[idx] + _35.dataB[idx];
}

